### PR TITLE
motion change

### PR DESCRIPTION
**Pull request by umangraval**

### CODE REVIEW

**Comment by darshkpatel** [comment]
I tried it out on my phone and here's what I found:
* All notes sound the same at any given point of motion
* Motion while holding a key does nothing

**Comment by darshkpatel** [comment]
Also, there are merge conflicts with master

**Comment by darshkpatel** [comment]
Most likely [Transport](https://tonejs.github.io/docs/13.8.25/Transport) would have to be utilized
or a simpler implementation would be to something like this on every value update from motion 
```
 pitch_shift = new Tone.PitchShift({
    pitch: mean_change_in_motion
    }).toDestination();
```

**Comment by umangraval** [comment]
> I tried it out on my phone and here's what I found:
> 
> * All notes sound the same at any given point of motion
> * Motion while holding a key does nothing

Try out different instruments like string. All the notes in piano almost sound the same but they are changing when you rotate around x-axis.

**Comment by darshkpatel** [comment]
Updates on this? @umangraval

**Comment by umangraval** [comment]
waiting for devam's fix. then i'll add my functions to it

**Comment by darshkpatel** [comment]
Changing Sensitivity isn't of much help

**Pull request merged**
